<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\AiChromeProxy.Application\AiChromeProxy.Application.csproj" />
    <ProjectReference Include="..\AiChromeProxy.Client\AiChromeProxy.Client.csproj" />
    <ProjectReference Include="..\AiChromeProxy.Domain\AiChromeProxy.Domain.csproj" />
    <ProjectReference Include="..\AiChromeProxy.Infrastructure\AiChromeProxy.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.12" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
